=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "activity".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.string :key
      t.decimal :owner_id
      t.string :owner_type
      t.string :parameters
      t.decimal :recipient_id
      t.string :recipient_type
      t.decimal :trackable_id
      t.string :trackable_type
      t.datetime :updated_at

      t.timestamps
    end

    create_table "answer".pluralize.to_sym, id: false do |t|
      t.decimal :author_id
      t.decimal :benefit_type
      t.decimal :chosen
      t.string :content
      t.decimal :contributing_group_id
      t.datetime :created_at
      t.decimal :id
      t.string :idea_category
      t.string :outcome
      t.decimal :question_id
      t.string :supporting_document_content_type
      t.string :supporting_document_file_name
      t.decimal :supporting_document_file_size
      t.datetime :supporting_document_updated_at
      t.string :supporting_video_content_type
      t.string :supporting_video_file_name
      t.decimal :supporting_video_file_size
      t.datetime :supporting_video_updated_at
      t.datetime :updated_at
      t.decimal :upvote_count
      t.decimal :value

      t.timestamps
    end

    create_table "answer_comment".pluralize.to_sym, id: false do |t|
      t.decimal :answer_id
      t.decimal :approved
      t.decimal :author_id
      t.string :content
      t.datetime :created_at
      t.decimal :id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "answer_expense".pluralize.to_sym, id: false do |t|
      t.decimal :answer_id
      t.decimal :expense_id
      t.decimal :id
      t.decimal :quantity

      t.timestamps
    end

    create_table "answer_upvote".pluralize.to_sym, id: false do |t|
      t.decimal :answer_id
      t.decimal :author_id
      t.datetime :created_at
      t.decimal :id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "badge".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :image_content_type
      t.string :image_file_name
      t.decimal :image_file_size
      t.datetime :image_updated_at
      t.string :label
      t.decimal :points
      t.datetime :updated_at

      t.timestamps
    end

    create_table "budget".pluralize.to_sym, id: false do |t|
      t.decimal :approver_id
      t.string :comments
      t.datetime :created_at
      t.string :decline_reason
      t.string :description
      t.decimal :group_id
      t.decimal :id
      t.decimal :is_approved
      t.decimal :requester_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "budget_item".pluralize.to_sym, id: false do |t|
      t.decimal :available_amount
      t.decimal :budget_id
      t.datetime :created_at
      t.decimal :estimated_amount
      t.datetime :estimated_date
      t.decimal :id
      t.decimal :is_done
      t.decimal :is_private
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "campaign".pluralize.to_sym, id: false do |t|
      t.string :banner_content_type
      t.string :banner_file_name
      t.decimal :banner_file_size
      t.datetime :banner_updated_at
      t.datetime :created_at
      t.string :description
      t.datetime :_end
      t.decimal :enterprise_id
      t.decimal :id
      t.string :image_content_type
      t.string :image_file_name
      t.decimal :image_file_size
      t.datetime :image_updated_at
      t.decimal :nb_invites
      t.decimal :owner_id
      t.datetime :start
      t.decimal :status
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "campaign_invitation".pluralize.to_sym, id: false do |t|
      t.decimal :campaign_id
      t.datetime :created_at
      t.decimal :email_sent
      t.decimal :id
      t.decimal :response
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "campaigns_group".pluralize.to_sym, id: false do |t|
      t.decimal :campaign_id
      t.decimal :group_id
      t.decimal :id

      t.timestamps
    end

    create_table "campaigns_manager".pluralize.to_sym, id: false do |t|
      t.decimal :campaign_id
      t.decimal :id
      t.decimal :user_id

      t.timestamps
    end

    create_table "campaigns_segment".pluralize.to_sym, id: false do |t|
      t.decimal :campaign_id
      t.decimal :id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "checklist".pluralize.to_sym, id: false do |t|
      t.decimal :author_id
      t.decimal :budget_id
      t.datetime :created_at
      t.decimal :id
      t.decimal :initiative_id
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "checklist_item".pluralize.to_sym, id: false do |t|
      t.decimal :checklist_id
      t.datetime :created_at
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :is_done
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "ckeditor_asset".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :data_content_type
      t.string :data_file_name
      t.decimal :data_file_size
      t.string :data_fingerprint
      t.decimal :height
      t.decimal :id
      t.string :type
      t.datetime :updated_at
      t.decimal :width

      t.timestamps
    end

    create_table "clockwork_database_event".pluralize.to_sym, id: false do |t|
      t.string :at
      t.datetime :created_at
      t.string :day
      t.decimal :disabled
      t.decimal :enterprise_id
      t.decimal :frequency_period_id
      t.decimal :frequency_quantity
      t.decimal :id
      t.string :job_name
      t.string :method_args
      t.string :method_name
      t.string :name
      t.string :tz
      t.datetime :updated_at

      t.timestamps
    end

    create_table "csvfile".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :download_file_content_type
      t.string :download_file_file_name
      t.decimal :download_file_file_size
      t.string :download_file_name
      t.datetime :download_file_updated_at
      t.decimal :group_id
      t.decimal :id
      t.string :import_file_content_type
      t.string :import_file_file_name
      t.decimal :import_file_file_size
      t.datetime :import_file_updated_at
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "custom_text".pluralize.to_sym, id: false do |t|
      t.string :badge
      t.string :dci_abbreviation
      t.string :dci_full_title
      t.decimal :enterprise_id
      t.string :erg
      t.decimal :id
      t.string :member_preference
      t.string :outcome
      t.string :parent
      t.string :privacy_statement
      t.string :program
      t.string :segment
      t.string :structure
      t.string :sub_erg

      t.timestamps
    end

    create_table "detached_field".pluralize.to_sym, id: false do |t|
      t.decimal :alternative_layout
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.decimal :match_exclude
      t.decimal :match_polarity
      t.decimal :max
      t.decimal :min
      t.string :options_text
      t.decimal :required
      t.string :title
      t.string :type
      t.datetime :updated_at

      t.timestamps
    end

    create_table "detached_field_answer".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :detached_field_id
      t.decimal :id
      t.datetime :updated_at
      t.string :value

      t.timestamps
    end

    create_table "email".pluralize.to_sym, id: false do |t|
      t.string :content
      t.datetime :created_at
      t.string :description
      t.decimal :enterprise_id
      t.decimal :id
      t.string :mailer_method
      t.string :mailer_name
      t.string :name
      t.string :subject
      t.string :template
      t.datetime :updated_at

      t.timestamps
    end

    create_table "email_variable".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :downcase
      t.decimal :email_id
      t.decimal :enterprise_email_variable_id
      t.decimal :id
      t.decimal :pluralize
      t.decimal :titleize
      t.decimal :upcase
      t.datetime :updated_at

      t.timestamps
    end

    create_table "enterpris".pluralize.to_sym, id: false do |t|
      t.string :banner_content_type
      t.string :banner_file_name
      t.decimal :banner_file_size
      t.datetime :banner_updated_at
      t.string :cdo_message
      t.string :cdo_picture_content_type
      t.string :cdo_picture_file_name
      t.decimal :cdo_picture_file_size
      t.datetime :cdo_picture_updated_at
      t.decimal :collaborate_module_enabled
      t.string :company_video_url
      t.datetime :created_at
      t.string :default_from_email_address
      t.string :default_from_email_display_name
      t.decimal :disable_emails
      t.decimal :disable_likes
      t.decimal :enable_pending_comments
      t.decimal :enable_rewards
      t.decimal :enable_social_media
      t.decimal :has_enabled_onboarding_email
      t.decimal :has_enabled_saml
      t.string :home_message
      t.decimal :id
      t.string :idp_cert
      t.string :idp_entity_id
      t.string :idp_slo_target_url
      t.string :idp_sso_target_url
      t.string :iframe_calendar_token
      t.decimal :mentorship_module_enabled
      t.string :name
      t.string :onboarding_sponsor_media_content_type
      t.string :onboarding_sponsor_media_file_name
      t.decimal :onboarding_sponsor_media_file_size
      t.datetime :onboarding_sponsor_media_updated_at
      t.decimal :plan_module_enabled
      t.string :privacy_statement
      t.decimal :redirect_all_emails
      t.string :redirect_email_contact
      t.string :saml_first_name_mapping
      t.string :saml_last_name_mapping
      t.decimal :scope_module_enabled
      t.string :sp_entity_id
      t.decimal :theme_id
      t.string :time_zone
      t.datetime :updated_at
      t.string :xml_sso_config_content_type
      t.string :xml_sso_config_file_name
      t.decimal :xml_sso_config_file_size
      t.datetime :xml_sso_config_updated_at
      t.decimal :yammer_group_sync
      t.decimal :yammer_import
      t.string :yammer_token

      t.timestamps
    end

    create_table "enterprise_email_variable".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :description
      t.decimal :enterprise_id
      t.string :example
      t.decimal :id
      t.string :key
      t.datetime :updated_at

      t.timestamps
    end

    create_table "expense".pluralize.to_sym, id: false do |t|
      t.decimal :category_id
      t.decimal :enterprise_id
      t.decimal :id
      t.decimal :income
      t.string :name
      t.decimal :price

      t.timestamps
    end

    create_table "expense_category".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.string :icon_content_type
      t.string :icon_file_name
      t.decimal :icon_file_size
      t.datetime :icon_updated_at
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "field".pluralize.to_sym, id: false do |t|
      t.decimal :alternative_layout
      t.datetime :created_at
      t.decimal :elasticsearch_only
      t.decimal :enterprise_id
      t.string :field_type
      t.decimal :gamification_value
      t.decimal :group_id
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :match_exclude
      t.decimal :match_polarity
      t.decimal :match_weight
      t.decimal :max
      t.decimal :min
      t.string :options_text
      t.decimal :poll_id
      t.decimal :private
      t.decimal :required
      t.string :saml_attribute
      t.decimal :show_on_vcard
      t.string :title
      t.string :type
      t.datetime :updated_at

      t.timestamps
    end

    create_table "folder".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :group_id
      t.decimal :id
      t.string :name
      t.decimal :parent_id
      t.string :password_digest
      t.decimal :password_protected
      t.datetime :updated_at

      t.timestamps
    end

    create_table "folder_share".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :folder_id
      t.decimal :group_id
      t.decimal :id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "frequency_period".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "graph".pluralize.to_sym, id: false do |t|
      t.decimal :aggregation_id
      t.datetime :created_at
      t.string :custom_aggregation
      t.string :custom_field
      t.decimal :field_id
      t.decimal :id
      t.decimal :metrics_dashboard_id
      t.decimal :poll_id
      t.datetime :range_from
      t.datetime :range_to
      t.decimal :time_series
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group".pluralize.to_sym, id: false do |t|
      t.decimal :active
      t.decimal :annual_budget
      t.string :banner_content_type
      t.string :banner_file_name
      t.decimal :banner_file_size
      t.datetime :banner_updated_at
      t.string :calendar_color
      t.string :company_video_url
      t.datetime :created_at
      t.decimal :default_mentor_group
      t.string :description
      t.decimal :enterprise_id
      t.decimal :group_category_id
      t.decimal :group_category_type_id
      t.string :home_message
      t.decimal :id
      t.string :latest_news_visibility
      t.string :layout
      t.decimal :lead_manager_id
      t.decimal :leftover_money
      t.string :logo_content_type
      t.string :logo_file_name
      t.decimal :logo_file_size
      t.datetime :logo_updated_at
      t.decimal :manager_id
      t.string :members_visibility
      t.string :messages_visibility
      t.string :name
      t.decimal :owner_id
      t.decimal :parent_id
      t.decimal :participation_score7days
      t.string :pending_users
      t.decimal :position
      t.decimal :private
      t.decimal :send_invitations
      t.string :short_description
      t.string :sponsor_image_content_type
      t.string :sponsor_image_file_name
      t.decimal :sponsor_image_file_size
      t.datetime :sponsor_image_updated_at
      t.decimal :total_weekly_points
      t.string :upcoming_events_visibility
      t.datetime :updated_at
      t.decimal :yammer_create_group
      t.decimal :yammer_group_created
      t.string :yammer_group_link
      t.string :yammer_group_name
      t.decimal :yammer_id
      t.decimal :yammer_sync_users

      t.timestamps
    end

    create_table "group_category".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :group_category_type_id
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group_category_type".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group_field".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :field_id
      t.decimal :group_id
      t.decimal :id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group_leader".pluralize.to_sym, id: false do |t|
      t.decimal :budget_approval
      t.datetime :created_at
      t.decimal :default_group_contact
      t.decimal :group_id
      t.decimal :group_leader_index
      t.decimal :group_leader_manage
      t.decimal :group_messages_create
      t.decimal :group_messages_index
      t.decimal :group_messages_manage
      t.decimal :group_posts_index
      t.decimal :group_resources_create
      t.decimal :group_resources_index
      t.decimal :group_resources_manage
      t.decimal :group_settings_manage
      t.decimal :groups_budgets_index
      t.decimal :groups_budgets_manage
      t.decimal :groups_budgets_request
      t.decimal :groups_insights_manage
      t.decimal :groups_layouts_manage
      t.decimal :groups_manage
      t.decimal :groups_members_index
      t.decimal :groups_members_manage
      t.decimal :id
      t.decimal :initiatives_create
      t.decimal :initiatives_index
      t.decimal :initiatives_manage
      t.decimal :manage_posts
      t.decimal :news_links_create
      t.decimal :news_links_index
      t.decimal :news_links_manage
      t.decimal :pending_comments_notifications_enabled
      t.decimal :pending_member_notifications_enabled
      t.decimal :pending_posts_notifications_enabled
      t.decimal :position
      t.string :position_name
      t.decimal :social_links_create
      t.decimal :social_links_index
      t.decimal :social_links_manage
      t.datetime :updated_at
      t.decimal :user_id
      t.decimal :user_role_id
      t.decimal :visible

      t.timestamps
    end

    create_table "group_message".pluralize.to_sym, id: false do |t|
      t.string :content
      t.datetime :created_at
      t.decimal :group_id
      t.decimal :id
      t.decimal :owner_id
      t.string :subject
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group_message_comment".pluralize.to_sym, id: false do |t|
      t.decimal :approved
      t.decimal :author_id
      t.string :content
      t.datetime :created_at
      t.decimal :id
      t.decimal :message_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "group_messages_segment".pluralize.to_sym, id: false do |t|
      t.decimal :group_message_id
      t.decimal :id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "group_update".pluralize.to_sym, id: false do |t|
      t.string :comments
      t.datetime :created_at
      t.string :data
      t.decimal :group_id
      t.decimal :id
      t.decimal :owner_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "groups_metrics_dashboard".pluralize.to_sym, id: false do |t|
      t.decimal :group_id
      t.decimal :id
      t.decimal :metrics_dashboard_id

      t.timestamps
    end

    create_table "groups_poll".pluralize.to_sym, id: false do |t|
      t.decimal :group_id
      t.decimal :id
      t.decimal :poll_id

      t.timestamps
    end

    create_table "initiative".pluralize.to_sym, id: false do |t|
      t.decimal :actual_funding
      t.decimal :budget_item_id
      t.datetime :created_at
      t.string :description
      t.datetime :_end
      t.decimal :estimated_funding
      t.decimal :finished_expenses
      t.decimal :id
      t.string :location
      t.decimal :max_attendees
      t.string :name
      t.decimal :owner_group_id
      t.decimal :owner_id
      t.string :picture_content_type
      t.string :picture_file_name
      t.decimal :picture_file_size
      t.datetime :picture_updated_at
      t.decimal :pillar_id
      t.datetime :start
      t.datetime :updated_at

      t.timestamps
    end

    create_table "initiative_comment".pluralize.to_sym, id: false do |t|
      t.decimal :approved
      t.string :content
      t.datetime :created_at
      t.decimal :id
      t.decimal :initiative_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "initiative_expense".pluralize.to_sym, id: false do |t|
      t.decimal :amount
      t.datetime :created_at
      t.string :description
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :owner_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "initiative_field".pluralize.to_sym, id: false do |t|
      t.decimal :field_id
      t.decimal :id
      t.decimal :initiative_id

      t.timestamps
    end

    create_table "initiative_group".pluralize.to_sym, id: false do |t|
      t.decimal :group_id
      t.decimal :id
      t.decimal :initiative_id

      t.timestamps
    end

    create_table "initiative_invitee".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :user_id

      t.timestamps
    end

    create_table "initiative_participating_group".pluralize.to_sym, id: false do |t|
      t.decimal :group_id
      t.decimal :id
      t.decimal :initiative_id

      t.timestamps
    end

    create_table "initiative_segment".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "initiative_update".pluralize.to_sym, id: false do |t|
      t.string :comments
      t.datetime :created_at
      t.string :data
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :owner_id
      t.datetime :report_date
      t.datetime :updated_at

      t.timestamps
    end

    create_table "initiative_user".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :initiative_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "inline_response_200".pluralize.to_sym, id: false do |t|
      t.boolean :exists

      t.timestamps
    end

    create_table "inline_response_200_1".pluralize.to_sym, id: false do |t|
      t.decimal :count

      t.timestamps
    end

    create_table "inline_response_200_2".pluralize.to_sym, id: false do |t|
      t.decimal :count

      t.timestamps
    end

    create_table "invitation_segments_group".pluralize.to_sym, id: false do |t|
      t.decimal :group_id
      t.decimal :id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "like".pluralize.to_sym, id: false do |t|
      t.decimal :answer_id
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.decimal :news_feed_link_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentoring".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentee_id
      t.decimal :mentor_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentoring_interest".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentoring_request".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :mentoring_type
      t.string :notes
      t.decimal :receiver_id
      t.decimal :sender_id
      t.string :status
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentoring_request_interest".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_interest_id
      t.decimal :mentoring_request_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentoring_session".pluralize.to_sym, id: false do |t|
      t.string :access_token
      t.datetime :created_at
      t.decimal :creator_id
      t.datetime :_end
      t.decimal :enterprise_id
      t.string :format
      t.decimal :id
      t.string :link
      t.string :notes
      t.datetime :start
      t.string :status
      t.datetime :updated_at
      t.string :video_room_name

      t.timestamps
    end

    create_table "mentoring_session_comment".pluralize.to_sym, id: false do |t|
      t.string :content
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_session_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentoring_session_topic".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_interest_id
      t.decimal :mentoring_session_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentoring_type".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentorship_availability".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :day
      t.string :_end
      t.decimal :id
      t.string :start
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentorship_campaign".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentorship_campaign_mentee".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentorship_campaign_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentorship_campaign_mentor".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentorship_campaign_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentorship_campaign_mentoring_interest".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_interest_id
      t.decimal :mentorship_campaign_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "mentorship_interest".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_interest_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentorship_rating".pluralize.to_sym, id: false do |t|
      t.string :comments
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_session_id
      t.decimal :okrs_achieved
      t.decimal :rating
      t.datetime :updated_at
      t.decimal :user_id
      t.decimal :valuable

      t.timestamps
    end

    create_table "mentorship_session".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_session_id
      t.string :role
      t.string :status
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "mentorship_type".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :mentoring_type_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "metrics_dashboard".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :name
      t.decimal :owner_id
      t.string :shareable_token
      t.datetime :updated_at

      t.timestamps
    end

    create_table "metrics_dashboards_segment".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :metrics_dashboard_id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "mobile_field".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :field_id
      t.decimal :id
      t.decimal :index
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_feed".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :group_id
      t.decimal :id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_feed_link".pluralize.to_sym, id: false do |t|
      t.decimal :approved
      t.datetime :archived_at
      t.datetime :created_at
      t.decimal :group_message_id
      t.decimal :id
      t.decimal :is_pinned
      t.decimal :news_feed_id
      t.decimal :news_link_id
      t.decimal :social_link_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_feed_link_segment".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :group_messages_segment_id
      t.decimal :id
      t.decimal :news_feed_link_id
      t.decimal :news_link_segment_id
      t.decimal :segment_id
      t.decimal :social_link_segment_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_link".pluralize.to_sym, id: false do |t|
      t.decimal :author_id
      t.datetime :created_at
      t.string :description
      t.decimal :group_id
      t.decimal :id
      t.string :picture_content_type
      t.string :picture_file_name
      t.decimal :picture_file_size
      t.datetime :picture_updated_at
      t.string :title
      t.datetime :updated_at
      t.string :url

      t.timestamps
    end

    create_table "news_link_comment".pluralize.to_sym, id: false do |t|
      t.decimal :approved
      t.decimal :author_id
      t.string :content
      t.datetime :created_at
      t.decimal :id
      t.decimal :news_link_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_link_photo".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :file_content_type
      t.string :file_file_name
      t.decimal :file_file_size
      t.datetime :file_updated_at
      t.decimal :id
      t.decimal :news_link_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "news_link_segment".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :news_link_id
      t.decimal :segment_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "outcome".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :group_id
      t.decimal :id
      t.string :name
      t.datetime :updated_at

      t.timestamps
    end

    create_table "pillar".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.string :name
      t.decimal :outcome_id
      t.datetime :updated_at
      t.string :value_proposition

      t.timestamps
    end

    create_table "policy_group".pluralize.to_sym, id: false do |t|
      t.decimal :branding_manage
      t.decimal :budget_approval
      t.decimal :campaigns_create
      t.decimal :campaigns_index
      t.decimal :campaigns_manage
      t.datetime :created_at
      t.decimal :diversity_manage
      t.decimal :enterprise_manage
      t.decimal :enterprise_resources_create
      t.decimal :enterprise_resources_index
      t.decimal :enterprise_resources_manage
      t.decimal :global_calendar
      t.decimal :group_leader_index
      t.decimal :group_leader_manage
      t.decimal :group_messages_create
      t.decimal :group_messages_index
      t.decimal :group_messages_manage
      t.decimal :group_posts_index
      t.decimal :group_resources_create
      t.decimal :group_resources_index
      t.decimal :group_resources_manage
      t.decimal :group_settings_manage
      t.decimal :groups_budgets_index
      t.decimal :groups_budgets_manage
      t.decimal :groups_budgets_request
      t.decimal :groups_create
      t.decimal :groups_index
      t.decimal :groups_insights_manage
      t.decimal :groups_layouts_manage
      t.decimal :groups_manage
      t.decimal :groups_members_index
      t.decimal :groups_members_manage
      t.decimal :id
      t.decimal :initiatives_create
      t.decimal :initiatives_index
      t.decimal :initiatives_manage
      t.decimal :logs_view
      t.decimal :manage_all
      t.decimal :manage_posts
      t.decimal :mentorship_manage
      t.decimal :metrics_dashboards_create
      t.decimal :metrics_dashboards_index
      t.decimal :news_links_create
      t.decimal :news_links_index
      t.decimal :news_links_manage
      t.decimal :permissions_manage
      t.decimal :polls_create
      t.decimal :polls_index
      t.decimal :polls_manage
      t.decimal :segments_create
      t.decimal :segments_index
      t.decimal :segments_manage
      t.decimal :social_links_create
      t.decimal :social_links_index
      t.decimal :social_links_manage
      t.decimal :sso_manage
      t.datetime :updated_at
      t.decimal :user_id
      t.decimal :users_index
      t.decimal :users_manage

      t.timestamps
    end

    create_table "policy_group_template".pluralize.to_sym, id: false do |t|
      t.decimal :branding_manage
      t.decimal :budget_approval
      t.decimal :campaigns_create
      t.decimal :campaigns_index
      t.decimal :campaigns_manage
      t.datetime :created_at
      t.decimal :default
      t.decimal :diversity_manage
      t.decimal :enterprise_id
      t.decimal :enterprise_manage
      t.decimal :enterprise_resources_create
      t.decimal :enterprise_resources_index
      t.decimal :enterprise_resources_manage
      t.decimal :global_calendar
      t.decimal :group_leader_index
      t.decimal :group_leader_manage
      t.decimal :group_messages_create
      t.decimal :group_messages_index
      t.decimal :group_messages_manage
      t.decimal :group_posts_index
      t.decimal :group_resources_create
      t.decimal :group_resources_index
      t.decimal :group_resources_manage
      t.decimal :group_settings_manage
      t.decimal :groups_budgets_index
      t.decimal :groups_budgets_manage
      t.decimal :groups_budgets_request
      t.decimal :groups_create
      t.decimal :groups_index
      t.decimal :groups_insights_manage
      t.decimal :groups_layouts_manage
      t.decimal :groups_manage
      t.decimal :groups_members_index
      t.decimal :groups_members_manage
      t.decimal :id
      t.decimal :initiatives_create
      t.decimal :initiatives_index
      t.decimal :initiatives_manage
      t.decimal :logs_view
      t.decimal :manage_all
      t.decimal :manage_posts
      t.decimal :mentorship_manage
      t.decimal :metrics_dashboards_create
      t.decimal :metrics_dashboards_index
      t.string :name
      t.decimal :news_links_create
      t.decimal :news_links_index
      t.decimal :news_links_manage
      t.decimal :permissions_manage
      t.decimal :polls_create
      t.decimal :polls_index
      t.decimal :polls_manage
      t.decimal :segments_create
      t.decimal :segments_index
      t.decimal :segments_manage
      t.decimal :social_links_create
      t.decimal :social_links_index
      t.decimal :social_links_manage
      t.decimal :sso_manage
      t.datetime :updated_at
      t.decimal :user_role_id
      t.decimal :users_index
      t.decimal :users_manage

      t.timestamps
    end

    create_table "poll".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :description
      t.decimal :email_sent
      t.string :_end
      t.decimal :enterprise_id
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :nb_invitations
      t.decimal :owner_id
      t.string :start
      t.decimal :status
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "poll_response".pluralize.to_sym, id: false do |t|
      t.decimal :anonymous
      t.datetime :created_at
      t.string :data
      t.decimal :id
      t.decimal :poll_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "polls_segment".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :poll_id
      t.decimal :segment_id

      t.timestamps
    end

    create_table "question".pluralize.to_sym, id: false do |t|
      t.decimal :campaign_id
      t.string :conclusion
      t.datetime :created_at
      t.string :description
      t.decimal :id
      t.datetime :solved_at
      t.string :title
      t.datetime :updated_at

      t.timestamps
    end

    create_table "resource".pluralize.to_sym, id: false do |t|
      t.datetime :archived_at
      t.datetime :created_at
      t.decimal :enterprise_id
      t.string :file_content_type
      t.string :file_file_name
      t.decimal :file_file_size
      t.datetime :file_updated_at
      t.decimal :folder_id
      t.decimal :group_id
      t.decimal :id
      t.decimal :initiative_id
      t.decimal :mentoring_session_id
      t.decimal :owner_id
      t.string :resource_type
      t.string :title
      t.datetime :updated_at
      t.string :url

      t.timestamps
    end

    create_table "reward".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :description
      t.decimal :enterprise_id
      t.decimal :id
      t.string :label
      t.string :picture_content_type
      t.string :picture_file_name
      t.decimal :picture_file_size
      t.datetime :picture_updated_at
      t.decimal :points
      t.decimal :responsible_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "reward_action".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :key
      t.string :label
      t.decimal :points
      t.datetime :updated_at

      t.timestamps
    end

    create_table "sample".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.string :data
      t.decimal :id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "schema_migration".pluralize.to_sym, id: false do |t|
      t.string :version
      t.decimal :id

      t.timestamps
    end

    create_table "segment".pluralize.to_sym, id: false do |t|
      t.string :active_users_filter
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :id
      t.string :name
      t.decimal :owner_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "segment_rule".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :field_id
      t.decimal :id
      t.decimal :operator
      t.decimal :segment_id
      t.datetime :updated_at
      t.string :values

      t.timestamps
    end

    create_table "segmentation".pluralize.to_sym, id: false do |t|
      t.decimal :child_id
      t.datetime :created_at
      t.decimal :id
      t.decimal :parent_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "shared_metrics_dashboard".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :metrics_dashboard_id
      t.decimal :user_id

      t.timestamps
    end

    create_table "shared_news_feed_link".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :news_feed_id
      t.decimal :news_feed_link_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "social_link_segment".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :segment_id
      t.decimal :social_link_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "social_network_post".pluralize.to_sym, id: false do |t|
      t.decimal :author_id
      t.datetime :created_at
      t.string :embed_code
      t.decimal :group_id
      t.decimal :id
      t.datetime :updated_at
      t.string :url

      t.timestamps
    end

    create_table "sponsor".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :disable_sponsor_message
      t.decimal :id
      t.string :sponsor_media_content_type
      t.string :sponsor_media_file_name
      t.decimal :sponsor_media_file_size
      t.datetime :sponsor_media_updated_at
      t.string :sponsor_message
      t.string :sponsor_name
      t.string :sponsor_title
      t.decimal :sponsorable_id
      t.string :sponsorable_type
      t.datetime :updated_at

      t.timestamps
    end

    create_table "survey_manager".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :survey_id
      t.decimal :user_id

      t.timestamps
    end

    create_table "tag".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.string :name
      t.decimal :resource_id
      t.datetime :updated_at

      t.timestamps
    end

    create_table "theme".pluralize.to_sym, id: false do |t|
      t.decimal :default
      t.string :digest
      t.decimal :id
      t.string :logo_content_type
      t.string :logo_file_name
      t.decimal :logo_file_size
      t.string :logo_redirect_url
      t.datetime :logo_updated_at
      t.string :primary_color
      t.string :secondary_color
      t.decimal :use_secondary_color

      t.timestamps
    end

    create_table "topic".pluralize.to_sym, id: false do |t|
      t.decimal :category_id
      t.datetime :created_at
      t.decimal :enterprise_id
      t.datetime :expiration
      t.decimal :id
      t.string :statement
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "topic_feedback".pluralize.to_sym, id: false do |t|
      t.string :content
      t.datetime :created_at
      t.decimal :featured
      t.decimal :id
      t.decimal :topic_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.decimal :accepting_mentee_requests
      t.decimal :accepting_mentor_requests
      t.decimal :active
      t.string :auth_source
      t.string :avatar_content_type
      t.string :avatar_file_name
      t.decimal :avatar_file_size
      t.datetime :avatar_updated_at
      t.string :biography
      t.datetime :created_at
      t.decimal :credits
      t.datetime :current_sign_in_at
      t.string :current_sign_in_ip
      t.decimal :custom_policy_group
      t.string :data
      t.string :email
      t.string :encrypted_password
      t.decimal :enterprise_id
      t.decimal :failed_attempts
      t.string :firebase_token
      t.datetime :firebase_token_generated_at
      t.string :first_name
      t.decimal :groups_notifications_date
      t.decimal :groups_notifications_frequency
      t.decimal :id
      t.datetime :invitation_accepted_at
      t.datetime :invitation_created_at
      t.decimal :invitation_limit
      t.datetime :invitation_sent_at
      t.string :invitation_token
      t.decimal :invitations_count
      t.decimal :invited_by_id
      t.string :invited_by_type
      t.string :last_name
      t.datetime :last_sign_in_at
      t.string :last_sign_in_ip
      t.string :linkedin_profile_url
      t.datetime :locked_at
      t.decimal :mentee
      t.decimal :mentor
      t.string :mentorship_description
      t.decimal :participation_score7days
      t.decimal :points
      t.string :provider
      t.datetime :remember_created_at
      t.datetime :reset_password_sent_at
      t.string :reset_password_token
      t.decimal :sign_in_count
      t.string :time_zone
      t.string :tokens
      t.decimal :total_weekly_points
      t.string :uid
      t.string :unlock_token
      t.datetime :updated_at
      t.decimal :user_role_id
      t.string :yammer_token

      t.timestamps
    end

    create_table "user_group".pluralize.to_sym, id: false do |t|
      t.decimal :accepted_member
      t.datetime :created_at
      t.string :data
      t.decimal :group_id
      t.decimal :id
      t.decimal :total_weekly_points
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "user_reward".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :id
      t.decimal :points
      t.decimal :reward_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "user_reward_action".pluralize.to_sym, id: false do |t|
      t.decimal :answer_comment_id
      t.decimal :answer_id
      t.decimal :answer_upvote_id
      t.datetime :created_at
      t.decimal :group_message_comment_id
      t.decimal :group_message_id
      t.decimal :id
      t.decimal :initiative_comment_id
      t.decimal :initiative_id
      t.decimal :news_link_comment_id
      t.decimal :news_link_id
      t.decimal :operation
      t.decimal :points
      t.decimal :poll_response_id
      t.decimal :reward_action_id
      t.decimal :social_link_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "user_role".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :default
      t.decimal :enterprise_id
      t.decimal :id
      t.decimal :priority
      t.string :role_name
      t.string :role_type
      t.datetime :updated_at

      t.timestamps
    end

    create_table "users_segment".pluralize.to_sym, id: false do |t|
      t.decimal :id
      t.decimal :segment_id
      t.decimal :user_id

      t.timestamps
    end

    create_table "view".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :enterprise_id
      t.decimal :folder_id
      t.decimal :group_id
      t.decimal :id
      t.decimal :news_feed_link_id
      t.decimal :resource_id
      t.datetime :updated_at
      t.decimal :user_id

      t.timestamps
    end

    create_table "x_any".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "yammer_field_mapping".pluralize.to_sym, id: false do |t|
      t.datetime :created_at
      t.decimal :diverst_field_id
      t.decimal :enterprise_id
      t.decimal :id
      t.datetime :updated_at
      t.string :yammer_field_name

      t.timestamps
    end

  end
end
