=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ActivityController < ApplicationController

  def activity/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/create_change_stream_get_activities_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/create_change_stream_post_activities_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/exists_get_activities{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/exists_head_activities{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/replace_by_id_post_activities{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/replace_by_id_put_activities{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/replace_or_create_post_activities_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/replace_or_create_put_activities
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def activity/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
