=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AnswerUpvoteController < ApplicationController

  def answer_upvote/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/create_change_stream_get_answer_upvotes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/create_change_stream_post_answer_upvotes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/exists_get_answer_upvotes{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/exists_head_answer_upvotes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/replace_by_id_post_answer_upvotes{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/replace_by_id_put_answer_upvotes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/replace_or_create_post_answer_upvotes_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/replace_or_create_put_answer_upvotes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_upvote/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
