=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AnswerExpenseController < ApplicationController

  def answer_expense/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/create_change_stream_get_answer_expenses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/create_change_stream_post_answer_expenses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/exists_get_answer_expenses{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/exists_head_answer_expenses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/replace_by_id_post_answer_expenses{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/replace_by_id_put_answer_expenses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/replace_or_create_post_answer_expenses_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/replace_or_create_put_answer_expenses
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def answer_expense/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
