=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class BadgeController < ApplicationController

  def badge/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/create_change_stream_get_badges_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/create_change_stream_post_badges_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/exists_get_badges{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/exists_head_badges{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/replace_by_id_post_badges{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/replace_by_id_put_badges{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/replace_or_create_post_badges_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/replace_or_create_put_badges
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def badge/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
