=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class BudgetItemController < ApplicationController

  def budget_item/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/create_change_stream_get_budget_items_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/create_change_stream_post_budget_items_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/exists_get_budget_items{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/exists_head_budget_items{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/replace_by_id_post_budget_items{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/replace_by_id_put_budget_items{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/replace_or_create_post_budget_items_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/replace_or_create_put_budget_items
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget_item/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
