=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class BudgetController < ApplicationController

  def budget/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/create_change_stream_get_budgets_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/create_change_stream_post_budgets_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/exists_get_budgets{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/exists_head_budgets{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/replace_by_id_post_budgets{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/replace_by_id_put_budgets{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/replace_or_create_post_budgets_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/replace_or_create_put_budgets
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def budget/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
