=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CampaignInvitationController < ApplicationController

  def campaign_invitation/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/create_change_stream_get_campaign_invitations_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/create_change_stream_post_campaign_invitations_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/exists_get_campaign_invitations{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/exists_head_campaign_invitations{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/replace_by_id_post_campaign_invitations{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/replace_by_id_put_campaign_invitations{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/replace_or_create_post_campaign_invitations_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/replace_or_create_put_campaign_invitations
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign_invitation/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
