=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CampaignsSegmentController < ApplicationController

  def campaigns_segment/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/create_change_stream_get_campaigns_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/create_change_stream_post_campaigns_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/exists_get_campaigns_segments{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/exists_head_campaigns_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/replace_by_id_post_campaigns_segments{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/replace_by_id_put_campaigns_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/replace_or_create_post_campaigns_segments_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/replace_or_create_put_campaigns_segments
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_segment/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
