=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CampaignsManagerController < ApplicationController

  def campaigns_manager/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/create_change_stream_get_campaigns_managers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/create_change_stream_post_campaigns_managers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/exists_get_campaigns_managers{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/exists_head_campaigns_managers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/replace_by_id_post_campaigns_managers{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/replace_by_id_put_campaigns_managers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/replace_or_create_post_campaigns_managers_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/replace_or_create_put_campaigns_managers
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaigns_manager/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
