=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CampaignController < ApplicationController

  def campaign/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/create_change_stream_get_campaigns_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/create_change_stream_post_campaigns_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/exists_get_campaigns{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/exists_head_campaigns{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/replace_by_id_post_campaigns{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/replace_by_id_put_campaigns{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/replace_or_create_post_campaigns_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/replace_or_create_put_campaigns
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def campaign/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
