=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ChecklistController < ApplicationController

  def checklist/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/create_change_stream_get_checklists_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/create_change_stream_post_checklists_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/exists_get_checklists{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/exists_head_checklists{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/replace_by_id_post_checklists{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/replace_by_id_put_checklists{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/replace_or_create_post_checklists_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/replace_or_create_put_checklists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
