=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ChecklistItemController < ApplicationController

  def checklist_item/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/create_change_stream_get_checklist_items_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/create_change_stream_post_checklist_items_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/exists_get_checklist_items{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/exists_head_checklist_items{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/replace_by_id_post_checklist_items{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/replace_by_id_put_checklist_items{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/replace_or_create_post_checklist_items_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/replace_or_create_put_checklist_items
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def checklist_item/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
