=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CkeditorAssetController < ApplicationController

  def ckeditor_asset/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/create_change_stream_get_ckeditor_assets_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/create_change_stream_post_ckeditor_assets_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/exists_get_ckeditor_assets{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/exists_head_ckeditor_assets{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/replace_by_id_post_ckeditor_assets{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/replace_by_id_put_ckeditor_assets{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/replace_or_create_post_ckeditor_assets_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/replace_or_create_put_ckeditor_assets
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def ckeditor_asset/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
