=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CsvfileController < ApplicationController

  def csvfile/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/create_change_stream_get_csvfiles_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/create_change_stream_post_csvfiles_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/exists_get_csvfiles{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/exists_head_csvfiles{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/replace_by_id_post_csvfiles{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/replace_by_id_put_csvfiles{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/replace_or_create_post_csvfiles_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/replace_or_create_put_csvfiles
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def csvfile/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
