=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CustomTextController < ApplicationController

  def custom_text/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/create_change_stream_get_custom_texts_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/create_change_stream_post_custom_texts_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/exists_get_custom_texts{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/exists_head_custom_texts{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/replace_by_id_post_custom_texts{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/replace_by_id_put_custom_texts{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/replace_or_create_post_custom_texts_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/replace_or_create_put_custom_texts
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def custom_text/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
