=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class DetachedFieldController < ApplicationController

  def detached_field/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/create_change_stream_get_detached_fields_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/create_change_stream_post_detached_fields_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/exists_get_detached_fields{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/exists_head_detached_fields{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/replace_by_id_post_detached_fields{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/replace_by_id_put_detached_fields{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/replace_or_create_post_detached_fields_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/replace_or_create_put_detached_fields
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
