=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class DetachedFieldAnswerController < ApplicationController

  def detached_field_answer/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/create_change_stream_get_detached_field_answers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/create_change_stream_post_detached_field_answers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/exists_get_detached_field_answers{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/exists_head_detached_field_answers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/replace_by_id_post_detached_field_answers{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/replace_by_id_put_detached_field_answers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/replace_or_create_post_detached_field_answers_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/replace_or_create_put_detached_field_answers
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def detached_field_answer/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
