=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class EmailVariableController < ApplicationController

  def email_variable/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/create_change_stream_get_email_variables_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/create_change_stream_post_email_variables_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/exists_get_email_variables{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/exists_head_email_variables{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/replace_by_id_post_email_variables{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/replace_by_id_put_email_variables{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/replace_or_create_post_email_variables_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/replace_or_create_put_email_variables
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_variable/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
