=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class EnterprisController < ApplicationController

  def enterpris/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/create_change_stream_get_enterpris_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/create_change_stream_post_enterpris_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/exists_get_enterpris{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/exists_head_enterpris{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/replace_by_id_post_enterpris{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/replace_by_id_put_enterpris{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/replace_or_create_post_enterpris_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/replace_or_create_put_enterpris
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def enterpris/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
