=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ExpenseCategoryController < ApplicationController

  def expense_category/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/create_change_stream_get_expense_categories_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/create_change_stream_post_expense_categories_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/exists_get_expense_categories{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/exists_head_expense_categories{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/replace_by_id_post_expense_categories{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/replace_by_id_put_expense_categories{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/replace_or_create_post_expense_categories_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/replace_or_create_put_expense_categories
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense_category/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
