=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ExpenseController < ApplicationController

  def expense/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/create_change_stream_get_expenses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/create_change_stream_post_expenses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/exists_get_expenses{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/exists_head_expenses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/replace_by_id_post_expenses{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/replace_by_id_put_expenses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/replace_or_create_post_expenses_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/replace_or_create_put_expenses
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def expense/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
