=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class FieldController < ApplicationController

  def field/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/create_change_stream_get_fields_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/create_change_stream_post_fields_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/exists_get_fields{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/exists_head_fields{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/replace_by_id_post_fields{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/replace_by_id_put_fields{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/replace_or_create_post_fields_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/replace_or_create_put_fields
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def field/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
