=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class FolderShareController < ApplicationController

  def folder_share/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/create_change_stream_get_folder_shares_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/create_change_stream_post_folder_shares_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/exists_get_folder_shares{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/exists_head_folder_shares{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/replace_by_id_post_folder_shares{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/replace_by_id_put_folder_shares{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/replace_or_create_post_folder_shares_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/replace_or_create_put_folder_shares
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder_share/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
