=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class FolderController < ApplicationController

  def folder/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/create_change_stream_get_folders_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/create_change_stream_post_folders_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/exists_get_folders{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/exists_head_folders{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/replace_by_id_post_folders{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/replace_by_id_put_folders{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/replace_or_create_post_folders_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/replace_or_create_put_folders
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def folder/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
