=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class FrequencyPeriodController < ApplicationController

  def frequency_period/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/create_change_stream_get_frequency_periods_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/create_change_stream_post_frequency_periods_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/exists_get_frequency_periods{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/exists_head_frequency_periods{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/replace_by_id_post_frequency_periods{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/replace_by_id_put_frequency_periods{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/replace_or_create_post_frequency_periods_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/replace_or_create_put_frequency_periods
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def frequency_period/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
