=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class GroupController < ApplicationController

  def group/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/create_change_stream_get_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/create_change_stream_post_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/exists_get_groups{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/exists_head_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/replace_by_id_post_groups{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/replace_by_id_put_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/replace_or_create_post_groups_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/replace_or_create_put_groups
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
