=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class GroupsMetricsDashboardController < ApplicationController

  def groups_metrics_dashboard/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/create_change_stream_get_groups_metrics_dashboards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/create_change_stream_post_groups_metrics_dashboards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/exists_get_groups_metrics_dashboards{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/exists_head_groups_metrics_dashboards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/replace_by_id_post_groups_metrics_dashboards{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/replace_by_id_put_groups_metrics_dashboards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/replace_or_create_post_groups_metrics_dashboards_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/replace_or_create_put_groups_metrics_dashboards
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_metrics_dashboard/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
