=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class GroupMessageController < ApplicationController

  def group_message/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/create_change_stream_get_group_messages_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/create_change_stream_post_group_messages_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/exists_get_group_messages{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/exists_head_group_messages{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/replace_by_id_post_group_messages{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/replace_by_id_put_group_messages{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/replace_or_create_post_group_messages_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/replace_or_create_put_group_messages
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_message/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
