=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class GroupMessagesSegmentController < ApplicationController

  def group_messages_segment/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/create_change_stream_get_group_messages_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/create_change_stream_post_group_messages_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/exists_get_group_messages_segments{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/exists_head_group_messages_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/replace_by_id_post_group_messages_segments{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/replace_by_id_put_group_messages_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/replace_or_create_post_group_messages_segments_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/replace_or_create_put_group_messages_segments
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def group_messages_segment/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
