=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class GroupsPollController < ApplicationController

  def groups_poll/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/create_change_stream_get_groups_polls_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/create_change_stream_post_groups_polls_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/exists_get_groups_polls{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/exists_head_groups_polls{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/replace_by_id_post_groups_polls{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/replace_by_id_put_groups_polls{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/replace_or_create_post_groups_polls_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/replace_or_create_put_groups_polls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def groups_poll/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
