=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class InitiativeGroupController < ApplicationController

  def initiative_group/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/create_change_stream_get_initiative_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/create_change_stream_post_initiative_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/exists_get_initiative_groups{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/exists_head_initiative_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/replace_by_id_post_initiative_groups{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/replace_by_id_put_initiative_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/replace_or_create_post_initiative_groups_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/replace_or_create_put_initiative_groups
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_group/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
