=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class InitiativeInviteeController < ApplicationController

  def initiative_invitee/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/create_change_stream_get_initiative_invitees_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/create_change_stream_post_initiative_invitees_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/exists_get_initiative_invitees{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/exists_head_initiative_invitees{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/replace_by_id_post_initiative_invitees{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/replace_by_id_put_initiative_invitees{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/replace_or_create_post_initiative_invitees_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/replace_or_create_put_initiative_invitees
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_invitee/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
