=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class InitiativeUserController < ApplicationController

  def initiative_user/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/create_change_stream_get_initiative_users_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/create_change_stream_post_initiative_users_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/exists_get_initiative_users{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/exists_head_initiative_users{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/replace_by_id_post_initiative_users{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/replace_by_id_put_initiative_users{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/replace_or_create_post_initiative_users_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/replace_or_create_put_initiative_users
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_user/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
