=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class InitiativeParticipatingGroupController < ApplicationController

  def initiative_participating_group/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/create_change_stream_get_initiative_participating_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/create_change_stream_post_initiative_participating_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/exists_get_initiative_participating_groups{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/exists_head_initiative_participating_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/replace_by_id_post_initiative_participating_groups{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/replace_by_id_put_initiative_participating_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/replace_or_create_post_initiative_participating_groups_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/replace_or_create_put_initiative_participating_groups
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def initiative_participating_group/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
