=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class InvitationSegmentsGroupController < ApplicationController

  def invitation_segments_group/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/create_change_stream_get_invitation_segments_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/create_change_stream_post_invitation_segments_groups_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/exists_get_invitation_segments_groups{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/exists_head_invitation_segments_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/replace_by_id_post_invitation_segments_groups{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/replace_by_id_put_invitation_segments_groups{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/replace_or_create_post_invitation_segments_groups_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/replace_or_create_put_invitation_segments_groups
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def invitation_segments_group/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
