=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class LikeController < ApplicationController

  def like/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/create_change_stream_get_likes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/create_change_stream_post_likes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/exists_get_likes{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/exists_head_likes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/replace_by_id_post_likes{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/replace_by_id_put_likes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/replace_or_create_post_likes_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/replace_or_create_put_likes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def like/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
