=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class MentoringRequestController < ApplicationController

  def mentoring_request/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/create_change_stream_get_mentoring_requests_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/create_change_stream_post_mentoring_requests_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/exists_get_mentoring_requests{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/exists_head_mentoring_requests{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/replace_by_id_post_mentoring_requests{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/replace_by_id_put_mentoring_requests{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/replace_or_create_post_mentoring_requests_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/replace_or_create_put_mentoring_requests
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring_request/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
