=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class MentorshipCampaignMenteeController < ApplicationController

  def mentorship_campaign_mentee/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/create_change_stream_get_mentorship_campaign_mentees_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/create_change_stream_post_mentorship_campaign_mentees_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/exists_get_mentorship_campaign_mentees{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/exists_head_mentorship_campaign_mentees{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/replace_by_id_post_mentorship_campaign_mentees{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/replace_by_id_put_mentorship_campaign_mentees{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/replace_or_create_post_mentorship_campaign_mentees_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/replace_or_create_put_mentorship_campaign_mentees
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_campaign_mentee/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
