=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class MentorshipRatingController < ApplicationController

  def mentorship_rating/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/create_change_stream_get_mentorship_ratings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/create_change_stream_post_mentorship_ratings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/exists_get_mentorship_ratings{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/exists_head_mentorship_ratings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/replace_by_id_post_mentorship_ratings{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/replace_by_id_put_mentorship_ratings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/replace_or_create_post_mentorship_ratings_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/replace_or_create_put_mentorship_ratings
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_rating/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
