=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class MentorshipTypeController < ApplicationController

  def mentorship_type/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/create_change_stream_get_mentorship_types_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/create_change_stream_post_mentorship_types_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/exists_get_mentorship_types{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/exists_head_mentorship_types{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/replace_by_id_post_mentorship_types{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/replace_by_id_put_mentorship_types{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/replace_or_create_post_mentorship_types_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/replace_or_create_put_mentorship_types
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentorship_type/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
