=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class MentoringController < ApplicationController

  def mentoring/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/create_change_stream_get_mentorings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/create_change_stream_post_mentorings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/exists_get_mentorings{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/exists_head_mentorings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/replace_by_id_post_mentorings{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/replace_by_id_put_mentorings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/replace_or_create_post_mentorings_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/replace_or_create_put_mentorings
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def mentoring/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
