=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class NewsFeedController < ApplicationController

  def news_feed/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/create_change_stream_get_news_feeds_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/create_change_stream_post_news_feeds_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/exists_get_news_feeds{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/exists_head_news_feeds{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/replace_by_id_post_news_feeds{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/replace_by_id_put_news_feeds{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/replace_or_create_post_news_feeds_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/replace_or_create_put_news_feeds
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_feed/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
