=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class NewsLinkController < ApplicationController

  def news_link/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/create_change_stream_get_news_links_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/create_change_stream_post_news_links_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/exists_get_news_links{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/exists_head_news_links{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/replace_by_id_post_news_links{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/replace_by_id_put_news_links{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/replace_or_create_post_news_links_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/replace_or_create_put_news_links
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
