=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class NewsLinkPhotoController < ApplicationController

  def news_link_photo/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/create_change_stream_get_news_link_photos_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/create_change_stream_post_news_link_photos_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/exists_get_news_link_photos{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/exists_head_news_link_photos{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/replace_by_id_post_news_link_photos{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/replace_by_id_put_news_link_photos{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/replace_or_create_post_news_link_photos_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/replace_or_create_put_news_link_photos
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def news_link_photo/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
