=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class OutcomeController < ApplicationController

  def outcome/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/create_change_stream_get_outcomes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/create_change_stream_post_outcomes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/exists_get_outcomes{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/exists_head_outcomes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/replace_by_id_post_outcomes{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/replace_by_id_put_outcomes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/replace_or_create_post_outcomes_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/replace_or_create_put_outcomes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def outcome/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
