=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PillarController < ApplicationController

  def pillar/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/create_change_stream_get_pillars_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/create_change_stream_post_pillars_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/exists_get_pillars{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/exists_head_pillars{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/replace_by_id_post_pillars{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/replace_by_id_put_pillars{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/replace_or_create_post_pillars_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/replace_or_create_put_pillars
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def pillar/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
