=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PolicyGroupTemplateController < ApplicationController

  def policy_group_template/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/create_change_stream_get_policy_group_templates_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/create_change_stream_post_policy_group_templates_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/exists_get_policy_group_templates{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/exists_head_policy_group_templates{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/replace_by_id_post_policy_group_templates{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/replace_by_id_put_policy_group_templates{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/replace_or_create_post_policy_group_templates_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/replace_or_create_put_policy_group_templates
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def policy_group_template/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
