=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PollResponseController < ApplicationController

  def poll_response/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/create_change_stream_get_poll_responses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/create_change_stream_post_poll_responses_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/exists_get_poll_responses{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/exists_head_poll_responses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/replace_by_id_post_poll_responses{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/replace_by_id_put_poll_responses{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/replace_or_create_post_poll_responses_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/replace_or_create_put_poll_responses
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll_response/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
