=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PollController < ApplicationController

  def poll/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/create_change_stream_get_polls_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/create_change_stream_post_polls_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/exists_get_polls{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/exists_head_polls{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/replace_by_id_post_polls{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/replace_by_id_put_polls{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/replace_or_create_post_polls_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/replace_or_create_put_polls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def poll/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
