=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class QuestionController < ApplicationController

  def question/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/create_change_stream_get_questions_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/create_change_stream_post_questions_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/exists_get_questions{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/exists_head_questions{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/replace_by_id_post_questions{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/replace_by_id_put_questions{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/replace_or_create_post_questions_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/replace_or_create_put_questions
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def question/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
