=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ResourceController < ApplicationController

  def resource/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/create_change_stream_get_resources_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/create_change_stream_post_resources_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/exists_get_resources{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/exists_head_resources{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/replace_by_id_post_resources{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/replace_by_id_put_resources{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/replace_or_create_post_resources_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/replace_or_create_put_resources
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def resource/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
