=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class RewardController < ApplicationController

  def reward/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/create_change_stream_get_rewards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/create_change_stream_post_rewards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/exists_get_rewards{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/exists_head_rewards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/replace_by_id_post_rewards{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/replace_by_id_put_rewards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/replace_or_create_post_rewards_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/replace_or_create_put_rewards
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def reward/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
