=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SampleController < ApplicationController

  def sample/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/create_change_stream_get_samples_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/create_change_stream_post_samples_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/exists_get_samples{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/exists_head_samples{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/replace_by_id_post_samples{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/replace_by_id_put_samples{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/replace_or_create_post_samples_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/replace_or_create_put_samples
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sample/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
