=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SchemaMigrationController < ApplicationController

  def schema_migration/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/create_change_stream_get_schema_migrations_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/create_change_stream_post_schema_migrations_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/exists_get_schema_migrations{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/exists_head_schema_migrations{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/replace_by_id_post_schema_migrations{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/replace_by_id_put_schema_migrations{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/replace_or_create_post_schema_migrations_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/replace_or_create_put_schema_migrations
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def schema_migration/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
