=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SegmentController < ApplicationController

  def segment/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/create_change_stream_get_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/create_change_stream_post_segments_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/exists_get_segments{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/exists_head_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/replace_by_id_post_segments{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/replace_by_id_put_segments{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/replace_or_create_post_segments_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/replace_or_create_put_segments
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def segment/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
