=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SharedNewsFeedLinkController < ApplicationController

  def shared_news_feed_link/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/create_change_stream_get_shared_news_feed_links_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/create_change_stream_post_shared_news_feed_links_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/exists_get_shared_news_feed_links{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/exists_head_shared_news_feed_links{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/replace_by_id_post_shared_news_feed_links{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/replace_by_id_put_shared_news_feed_links{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/replace_or_create_post_shared_news_feed_links_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/replace_or_create_put_shared_news_feed_links
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shared_news_feed_link/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
