=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SponsorController < ApplicationController

  def sponsor/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/create_change_stream_get_sponsors_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/create_change_stream_post_sponsors_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/exists_get_sponsors{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/exists_head_sponsors{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/replace_by_id_post_sponsors{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/replace_by_id_put_sponsors{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/replace_or_create_post_sponsors_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/replace_or_create_put_sponsors
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sponsor/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
