=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SurveyManagerController < ApplicationController

  def survey_manager/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/create_change_stream_get_survey_managers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/create_change_stream_post_survey_managers_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/exists_get_survey_managers{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/exists_head_survey_managers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/replace_by_id_post_survey_managers{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/replace_by_id_put_survey_managers{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/replace_or_create_post_survey_managers_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/replace_or_create_put_survey_managers
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def survey_manager/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
