=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class TagController < ApplicationController

  def tag/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/create_change_stream_get_tags_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/create_change_stream_post_tags_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/exists_get_tags{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/exists_head_tags{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/replace_by_id_post_tags{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/replace_by_id_put_tags{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/replace_or_create_post_tags_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/replace_or_create_put_tags
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def tag/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
