=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ThemeController < ApplicationController

  def theme/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/create_change_stream_get_themes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/create_change_stream_post_themes_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/exists_get_themes{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/exists_head_themes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/replace_by_id_post_themes{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/replace_by_id_put_themes{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/replace_or_create_post_themes_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/replace_or_create_put_themes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def theme/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
