=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class TopicController < ApplicationController

  def topic/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/create_change_stream_get_topics_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/create_change_stream_post_topics_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/exists_get_topics{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/exists_head_topics{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/replace_by_id_post_topics{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/replace_by_id_put_topics{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/replace_or_create_post_topics_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/replace_or_create_put_topics
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
