=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class TopicFeedbackController < ApplicationController

  def topic_feedback/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/create_change_stream_get_topic_feedbacks_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/create_change_stream_post_topic_feedbacks_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/exists_get_topic_feedbacks{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/exists_head_topic_feedbacks{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/replace_by_id_post_topic_feedbacks{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/replace_by_id_put_topic_feedbacks{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/replace_or_create_post_topic_feedbacks_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/replace_or_create_put_topic_feedbacks
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def topic_feedback/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
