=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UserRewardController < ApplicationController

  def user_reward/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/create_change_stream_get_user_rewards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/create_change_stream_post_user_rewards_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/exists_get_user_rewards{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/exists_head_user_rewards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/replace_by_id_post_user_rewards{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/replace_by_id_put_user_rewards{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/replace_or_create_post_user_rewards_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/replace_or_create_put_user_rewards
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
