=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UserRewardActionController < ApplicationController

  def user_reward_action/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/create_change_stream_get_user_reward_actions_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/create_change_stream_post_user_reward_actions_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/exists_get_user_reward_actions{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/exists_head_user_reward_actions{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/replace_by_id_post_user_reward_actions{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/replace_by_id_put_user_reward_actions{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/replace_or_create_post_user_reward_actions_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/replace_or_create_put_user_reward_actions
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_reward_action/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
