=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UserController < ApplicationController

  def user/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/create_change_stream_get_users_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/create_change_stream_post_users_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/exists_get_users{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/exists_head_users{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/replace_by_id_post_users{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/replace_by_id_put_users{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/replace_or_create_post_users_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/replace_or_create_put_users
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
