=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UserRoleController < ApplicationController

  def user_role/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/create_change_stream_get_user_roles_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/create_change_stream_post_user_roles_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/exists_get_user_roles{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/exists_head_user_roles{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/replace_by_id_post_user_roles{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/replace_by_id_put_user_roles{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/replace_or_create_post_user_roles_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/replace_or_create_put_user_roles
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_role/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
