=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class YammerFieldMappingController < ApplicationController

  def yammer_field_mapping/count
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/create_change_stream_get_yammer_field_mappings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/create_change_stream_post_yammer_field_mappings_change_stream
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/delete_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/exists_get_yammer_field_mappings{id}exists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/exists_head_yammer_field_mappings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/find
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/find_by_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/find_one
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/patch_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/prototype/patch_attributes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/replace_by_id_post_yammer_field_mappings{id}replace
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/replace_by_id_put_yammer_field_mappings{id}
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/replace_or_create_post_yammer_field_mappings_replace_or_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/replace_or_create_put_yammer_field_mappings
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/update_all
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def yammer_field_mapping/upsert_with_where
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
