=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class MentoringSession < ApplicationRecord
  validates_presence_of :creator_id
  validates_presence_of :_end
  validates_presence_of :format
  validates_presence_of :id
  validates_presence_of :start
  validates_presence_of :status

end
