=begin
diverst

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Reward < ApplicationRecord
  validates_presence_of :enterprise_id
  validates_presence_of :id
  validates_presence_of :points
  validates_presence_of :responsible_id

end
